/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.projectweb.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.projectweb.ui.internal.ProjectwebActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ProjectWebExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ProjectwebActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ProjectwebActivator.getInstance().getInjector(ProjectwebActivator.ORG_XTEXT_EXAMPLE_PROJECTWEB_PROJECTWEB);
	}
	
}
