/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.projectweb.projectWeb;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.projectweb.projectWeb.ProjectWebPackage
 * @generated
 */
public interface ProjectWebFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ProjectWebFactory eINSTANCE = org.xtext.example.projectweb.projectWeb.impl.ProjectWebFactoryImpl.init();

  /**
   * Returns a new object of class '<em>program Web</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>program Web</em>'.
   * @generated
   */
  programWeb createprogramWeb();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  ProjectWebPackage getProjectWebPackage();

} //ProjectWebFactory
