/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.projectweb.projectWeb;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.projectweb.projectWeb.ProjectWebFactory
 * @model kind="package"
 * @generated
 */
public interface ProjectWebPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "projectWeb";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/projectweb/ProjectWeb";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "projectWeb";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ProjectWebPackage eINSTANCE = org.xtext.example.projectweb.projectWeb.impl.ProjectWebPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.projectweb.projectWeb.impl.programWebImpl <em>program Web</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.projectweb.projectWeb.impl.programWebImpl
   * @see org.xtext.example.projectweb.projectWeb.impl.ProjectWebPackageImpl#getprogramWeb()
   * @generated
   */
  int PROGRAM_WEB = 0;

  /**
   * The feature id for the '<em><b>Declarations</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_WEB__DECLARATIONS = 0;

  /**
   * The feature id for the '<em><b>Nav</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_WEB__NAV = 1;

  /**
   * The feature id for the '<em><b>Goto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_WEB__GOTO = 2;

  /**
   * The feature id for the '<em><b>If</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_WEB__IF = 3;

  /**
   * The feature id for the '<em><b>Fonction</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_WEB__FONCTION = 4;

  /**
   * The feature id for the '<em><b>Proc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_WEB__PROC = 5;

  /**
   * The number of structural features of the '<em>program Web</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_WEB_FEATURE_COUNT = 6;


  /**
   * Returns the meta object for class '{@link org.xtext.example.projectweb.projectWeb.programWeb <em>program Web</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>program Web</em>'.
   * @see org.xtext.example.projectweb.projectWeb.programWeb
   * @generated
   */
  EClass getprogramWeb();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.projectweb.projectWeb.programWeb#getDeclarations <em>Declarations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Declarations</em>'.
   * @see org.xtext.example.projectweb.projectWeb.programWeb#getDeclarations()
   * @see #getprogramWeb()
   * @generated
   */
  EAttribute getprogramWeb_Declarations();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.projectweb.projectWeb.programWeb#getNav <em>Nav</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nav</em>'.
   * @see org.xtext.example.projectweb.projectWeb.programWeb#getNav()
   * @see #getprogramWeb()
   * @generated
   */
  EAttribute getprogramWeb_Nav();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.projectweb.projectWeb.programWeb#getGoto <em>Goto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Goto</em>'.
   * @see org.xtext.example.projectweb.projectWeb.programWeb#getGoto()
   * @see #getprogramWeb()
   * @generated
   */
  EAttribute getprogramWeb_Goto();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.projectweb.projectWeb.programWeb#getIf <em>If</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>If</em>'.
   * @see org.xtext.example.projectweb.projectWeb.programWeb#getIf()
   * @see #getprogramWeb()
   * @generated
   */
  EAttribute getprogramWeb_If();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.projectweb.projectWeb.programWeb#getFonction <em>Fonction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Fonction</em>'.
   * @see org.xtext.example.projectweb.projectWeb.programWeb#getFonction()
   * @see #getprogramWeb()
   * @generated
   */
  EAttribute getprogramWeb_Fonction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.projectweb.projectWeb.programWeb#getProc <em>Proc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Proc</em>'.
   * @see org.xtext.example.projectweb.projectWeb.programWeb#getProc()
   * @see #getprogramWeb()
   * @generated
   */
  EAttribute getprogramWeb_Proc();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ProjectWebFactory getProjectWebFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.projectweb.projectWeb.impl.programWebImpl <em>program Web</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.projectweb.projectWeb.impl.programWebImpl
     * @see org.xtext.example.projectweb.projectWeb.impl.ProjectWebPackageImpl#getprogramWeb()
     * @generated
     */
    EClass PROGRAM_WEB = eINSTANCE.getprogramWeb();

    /**
     * The meta object literal for the '<em><b>Declarations</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROGRAM_WEB__DECLARATIONS = eINSTANCE.getprogramWeb_Declarations();

    /**
     * The meta object literal for the '<em><b>Nav</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROGRAM_WEB__NAV = eINSTANCE.getprogramWeb_Nav();

    /**
     * The meta object literal for the '<em><b>Goto</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROGRAM_WEB__GOTO = eINSTANCE.getprogramWeb_Goto();

    /**
     * The meta object literal for the '<em><b>If</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROGRAM_WEB__IF = eINSTANCE.getprogramWeb_If();

    /**
     * The meta object literal for the '<em><b>Fonction</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROGRAM_WEB__FONCTION = eINSTANCE.getprogramWeb_Fonction();

    /**
     * The meta object literal for the '<em><b>Proc</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROGRAM_WEB__PROC = eINSTANCE.getprogramWeb_Proc();

  }

} //ProjectWebPackage
