/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.projectweb.projectWeb.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import org.xtext.example.projectweb.projectWeb.ProjectWebFactory;
import org.xtext.example.projectweb.projectWeb.programWeb;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>program Web</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class programWebTest extends TestCase {

	/**
	 * The fixture for this program Web test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected programWeb fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(programWebTest.class);
	}

	/**
	 * Constructs a new program Web test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public programWebTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this program Web test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(programWeb fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this program Web test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected programWeb getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(ProjectWebFactory.eINSTANCE.createprogramWeb());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //programWebTest
