/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.projectweb.projectWeb.tests;

import junit.framework.Test;
import junit.framework.TestSuite;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test suite for the '<em><b>projectWeb</b></em>' package.
 * <!-- end-user-doc -->
 * @generated
 */
public class ProjectWebTests extends TestSuite {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(suite());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static Test suite() {
		TestSuite suite = new ProjectWebTests("projectWeb Tests");
		return suite;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ProjectWebTests(String name) {
		super(name);
	}

} //ProjectWebTests
