/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.projectweb.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractProjectWebScopeProvider extends DelegatingScopeProvider {
}
