/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.projectweb


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ProjectWebStandaloneSetup extends ProjectWebStandaloneSetupGenerated {

	def static void doSetup() {
		new ProjectWebStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
