/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.projectweb.projectWeb.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

import org.xtext.example.projectweb.projectWeb.ProjectWebPackage;
import org.xtext.example.projectweb.projectWeb.programWeb;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>program Web</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.projectweb.projectWeb.impl.programWebImpl#getDeclarations <em>Declarations</em>}</li>
 *   <li>{@link org.xtext.example.projectweb.projectWeb.impl.programWebImpl#getNav <em>Nav</em>}</li>
 *   <li>{@link org.xtext.example.projectweb.projectWeb.impl.programWebImpl#getGoto <em>Goto</em>}</li>
 *   <li>{@link org.xtext.example.projectweb.projectWeb.impl.programWebImpl#getIf <em>If</em>}</li>
 *   <li>{@link org.xtext.example.projectweb.projectWeb.impl.programWebImpl#getFonction <em>Fonction</em>}</li>
 *   <li>{@link org.xtext.example.projectweb.projectWeb.impl.programWebImpl#getProc <em>Proc</em>}</li>
 * </ul>
 *
 * @generated
 */
public class programWebImpl extends MinimalEObjectImpl.Container implements programWeb
{
  /**
   * The cached value of the '{@link #getDeclarations() <em>Declarations</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDeclarations()
   * @generated
   * @ordered
   */
  protected EList<String> declarations;

  /**
   * The default value of the '{@link #getNav() <em>Nav</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNav()
   * @generated
   * @ordered
   */
  protected static final String NAV_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNav() <em>Nav</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNav()
   * @generated
   * @ordered
   */
  protected String nav = NAV_EDEFAULT;

  /**
   * The default value of the '{@link #getGoto() <em>Goto</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGoto()
   * @generated
   * @ordered
   */
  protected static final String GOTO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getGoto() <em>Goto</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGoto()
   * @generated
   * @ordered
   */
  protected String goto_ = GOTO_EDEFAULT;

  /**
   * The default value of the '{@link #getIf() <em>If</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIf()
   * @generated
   * @ordered
   */
  protected static final String IF_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getIf() <em>If</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIf()
   * @generated
   * @ordered
   */
  protected String if_ = IF_EDEFAULT;

  /**
   * The default value of the '{@link #getFonction() <em>Fonction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFonction()
   * @generated
   * @ordered
   */
  protected static final String FONCTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFonction() <em>Fonction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFonction()
   * @generated
   * @ordered
   */
  protected String fonction = FONCTION_EDEFAULT;

  /**
   * The default value of the '{@link #getProc() <em>Proc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProc()
   * @generated
   * @ordered
   */
  protected static final String PROC_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getProc() <em>Proc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProc()
   * @generated
   * @ordered
   */
  protected String proc = PROC_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected programWebImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ProjectWebPackage.Literals.PROGRAM_WEB;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<String> getDeclarations()
  {
    if (declarations == null)
    {
      declarations = new EDataTypeEList<String>(String.class, this, ProjectWebPackage.PROGRAM_WEB__DECLARATIONS);
    }
    return declarations;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getNav()
  {
    return nav;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNav(String newNav)
  {
    String oldNav = nav;
    nav = newNav;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ProjectWebPackage.PROGRAM_WEB__NAV, oldNav, nav));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getGoto()
  {
    return goto_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setGoto(String newGoto)
  {
    String oldGoto = goto_;
    goto_ = newGoto;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ProjectWebPackage.PROGRAM_WEB__GOTO, oldGoto, goto_));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getIf()
  {
    return if_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIf(String newIf)
  {
    String oldIf = if_;
    if_ = newIf;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ProjectWebPackage.PROGRAM_WEB__IF, oldIf, if_));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getFonction()
  {
    return fonction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFonction(String newFonction)
  {
    String oldFonction = fonction;
    fonction = newFonction;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ProjectWebPackage.PROGRAM_WEB__FONCTION, oldFonction, fonction));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getProc()
  {
    return proc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setProc(String newProc)
  {
    String oldProc = proc;
    proc = newProc;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ProjectWebPackage.PROGRAM_WEB__PROC, oldProc, proc));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ProjectWebPackage.PROGRAM_WEB__DECLARATIONS:
        return getDeclarations();
      case ProjectWebPackage.PROGRAM_WEB__NAV:
        return getNav();
      case ProjectWebPackage.PROGRAM_WEB__GOTO:
        return getGoto();
      case ProjectWebPackage.PROGRAM_WEB__IF:
        return getIf();
      case ProjectWebPackage.PROGRAM_WEB__FONCTION:
        return getFonction();
      case ProjectWebPackage.PROGRAM_WEB__PROC:
        return getProc();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ProjectWebPackage.PROGRAM_WEB__DECLARATIONS:
        getDeclarations().clear();
        getDeclarations().addAll((Collection<? extends String>)newValue);
        return;
      case ProjectWebPackage.PROGRAM_WEB__NAV:
        setNav((String)newValue);
        return;
      case ProjectWebPackage.PROGRAM_WEB__GOTO:
        setGoto((String)newValue);
        return;
      case ProjectWebPackage.PROGRAM_WEB__IF:
        setIf((String)newValue);
        return;
      case ProjectWebPackage.PROGRAM_WEB__FONCTION:
        setFonction((String)newValue);
        return;
      case ProjectWebPackage.PROGRAM_WEB__PROC:
        setProc((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ProjectWebPackage.PROGRAM_WEB__DECLARATIONS:
        getDeclarations().clear();
        return;
      case ProjectWebPackage.PROGRAM_WEB__NAV:
        setNav(NAV_EDEFAULT);
        return;
      case ProjectWebPackage.PROGRAM_WEB__GOTO:
        setGoto(GOTO_EDEFAULT);
        return;
      case ProjectWebPackage.PROGRAM_WEB__IF:
        setIf(IF_EDEFAULT);
        return;
      case ProjectWebPackage.PROGRAM_WEB__FONCTION:
        setFonction(FONCTION_EDEFAULT);
        return;
      case ProjectWebPackage.PROGRAM_WEB__PROC:
        setProc(PROC_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ProjectWebPackage.PROGRAM_WEB__DECLARATIONS:
        return declarations != null && !declarations.isEmpty();
      case ProjectWebPackage.PROGRAM_WEB__NAV:
        return NAV_EDEFAULT == null ? nav != null : !NAV_EDEFAULT.equals(nav);
      case ProjectWebPackage.PROGRAM_WEB__GOTO:
        return GOTO_EDEFAULT == null ? goto_ != null : !GOTO_EDEFAULT.equals(goto_);
      case ProjectWebPackage.PROGRAM_WEB__IF:
        return IF_EDEFAULT == null ? if_ != null : !IF_EDEFAULT.equals(if_);
      case ProjectWebPackage.PROGRAM_WEB__FONCTION:
        return FONCTION_EDEFAULT == null ? fonction != null : !FONCTION_EDEFAULT.equals(fonction);
      case ProjectWebPackage.PROGRAM_WEB__PROC:
        return PROC_EDEFAULT == null ? proc != null : !PROC_EDEFAULT.equals(proc);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (declarations: ");
    result.append(declarations);
    result.append(", nav: ");
    result.append(nav);
    result.append(", goto: ");
    result.append(goto_);
    result.append(", if: ");
    result.append(if_);
    result.append(", fonction: ");
    result.append(fonction);
    result.append(", proc: ");
    result.append(proc);
    result.append(')');
    return result.toString();
  }

} //programWebImpl
